server 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
-
-# check for command arguments
+# Check for cmd line arguments
 
 if [ $# -lt 4 ]
 then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
+# Assign variable parameters
 
-# Assign variable arguments
 path_to_file=$1
 ip=$2
 username=$3
@@ -16,14 +15,13 @@ path_to_ssh_key=$4
 
 # Disable strict host key checking
 
-scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:-/"
 
-# Check transfer outcome
+# Checking the transfer outcome
 
 if [ $? -eq 0 ]
 then
-    echo "Transfer Successful"
+	echo "Transfer Successful"
 else
-    echo "Transfer Failed"
+	echo "Tranfer failed"
 fi
-
